package com.srimin.demo01springbootquickstart.model;

public class Posts {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column posts.id
     *
     * @mbg.generated Tue Mar 24 23:33:57 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column posts.title
     *
     * @mbg.generated Tue Mar 24 23:33:57 CST 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column posts.gmt_create
     *
     * @mbg.generated Tue Mar 24 23:33:57 CST 2020
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column posts.gmt_modified
     *
     * @mbg.generated Tue Mar 24 23:33:57 CST 2020
     */
    private Long gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column posts.creator
     *
     * @mbg.generated Tue Mar 24 23:33:57 CST 2020
     */
    private Integer creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column posts.comment_count
     *
     * @mbg.generated Tue Mar 24 23:33:57 CST 2020
     */
    private Integer commentCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column posts.view_count
     *
     * @mbg.generated Tue Mar 24 23:33:57 CST 2020
     */
    private Integer viewCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column posts.like_count
     *
     * @mbg.generated Tue Mar 24 23:33:57 CST 2020
     */
    private Integer likeCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column posts.tag
     *
     * @mbg.generated Tue Mar 24 23:33:57 CST 2020
     */
    private String tag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column posts.content
     *
     * @mbg.generated Tue Mar 24 23:33:57 CST 2020
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column posts.id
     *
     * @return the value of posts.id
     *
     * @mbg.generated Tue Mar 24 23:33:57 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column posts.id
     *
     * @param id the value for posts.id
     *
     * @mbg.generated Tue Mar 24 23:33:57 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column posts.title
     *
     * @return the value of posts.title
     *
     * @mbg.generated Tue Mar 24 23:33:57 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column posts.title
     *
     * @param title the value for posts.title
     *
     * @mbg.generated Tue Mar 24 23:33:57 CST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column posts.gmt_create
     *
     * @return the value of posts.gmt_create
     *
     * @mbg.generated Tue Mar 24 23:33:57 CST 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column posts.gmt_create
     *
     * @param gmtCreate the value for posts.gmt_create
     *
     * @mbg.generated Tue Mar 24 23:33:57 CST 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column posts.gmt_modified
     *
     * @return the value of posts.gmt_modified
     *
     * @mbg.generated Tue Mar 24 23:33:57 CST 2020
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column posts.gmt_modified
     *
     * @param gmtModified the value for posts.gmt_modified
     *
     * @mbg.generated Tue Mar 24 23:33:57 CST 2020
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column posts.creator
     *
     * @return the value of posts.creator
     *
     * @mbg.generated Tue Mar 24 23:33:57 CST 2020
     */
    public Integer getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column posts.creator
     *
     * @param creator the value for posts.creator
     *
     * @mbg.generated Tue Mar 24 23:33:57 CST 2020
     */
    public void setCreator(Integer creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column posts.comment_count
     *
     * @return the value of posts.comment_count
     *
     * @mbg.generated Tue Mar 24 23:33:57 CST 2020
     */
    public Integer getCommentCount() {
        return commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column posts.comment_count
     *
     * @param commentCount the value for posts.comment_count
     *
     * @mbg.generated Tue Mar 24 23:33:57 CST 2020
     */
    public void setCommentCount(Integer commentCount) {
        this.commentCount = commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column posts.view_count
     *
     * @return the value of posts.view_count
     *
     * @mbg.generated Tue Mar 24 23:33:57 CST 2020
     */
    public Integer getViewCount() {
        return viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column posts.view_count
     *
     * @param viewCount the value for posts.view_count
     *
     * @mbg.generated Tue Mar 24 23:33:57 CST 2020
     */
    public void setViewCount(Integer viewCount) {
        this.viewCount = viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column posts.like_count
     *
     * @return the value of posts.like_count
     *
     * @mbg.generated Tue Mar 24 23:33:57 CST 2020
     */
    public Integer getLikeCount() {
        return likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column posts.like_count
     *
     * @param likeCount the value for posts.like_count
     *
     * @mbg.generated Tue Mar 24 23:33:57 CST 2020
     */
    public void setLikeCount(Integer likeCount) {
        this.likeCount = likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column posts.tag
     *
     * @return the value of posts.tag
     *
     * @mbg.generated Tue Mar 24 23:33:57 CST 2020
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column posts.tag
     *
     * @param tag the value for posts.tag
     *
     * @mbg.generated Tue Mar 24 23:33:57 CST 2020
     */
    public void setTag(String tag) {
        this.tag = tag == null ? null : tag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column posts.content
     *
     * @return the value of posts.content
     *
     * @mbg.generated Tue Mar 24 23:33:57 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column posts.content
     *
     * @param content the value for posts.content
     *
     * @mbg.generated Tue Mar 24 23:33:57 CST 2020
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}