package com.srimin.demo01springbootquickstart.mapper;

import com.srimin.demo01springbootquickstart.model.Posts;
import com.srimin.demo01springbootquickstart.model.PostsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PostsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts
     *
     * @mbg.generated Tue Mar 24 23:33:57 CST 2020
     */
    long countByExample(PostsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts
     *
     * @mbg.generated Tue Mar 24 23:33:57 CST 2020
     */
    int deleteByExample(PostsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts
     *
     * @mbg.generated Tue Mar 24 23:33:57 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts
     *
     * @mbg.generated Tue Mar 24 23:33:57 CST 2020
     */
    int insert(Posts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts
     *
     * @mbg.generated Tue Mar 24 23:33:57 CST 2020
     */
    int insertSelective(Posts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts
     *
     * @mbg.generated Tue Mar 24 23:33:57 CST 2020
     */
    List<Posts> selectByExampleWithBLOBs(PostsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts
     *
     * @mbg.generated Tue Mar 24 23:33:57 CST 2020
     */
    List<Posts> selectByExample(PostsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts
     *
     * @mbg.generated Tue Mar 24 23:33:57 CST 2020
     */
    Posts selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts
     *
     * @mbg.generated Tue Mar 24 23:33:57 CST 2020
     */
    int updateByExampleSelective(@Param("record") Posts record, @Param("example") PostsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts
     *
     * @mbg.generated Tue Mar 24 23:33:57 CST 2020
     */
    int updateByExampleWithBLOBs(@Param("record") Posts record, @Param("example") PostsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts
     *
     * @mbg.generated Tue Mar 24 23:33:57 CST 2020
     */
    int updateByExample(@Param("record") Posts record, @Param("example") PostsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts
     *
     * @mbg.generated Tue Mar 24 23:33:57 CST 2020
     */
    int updateByPrimaryKeySelective(Posts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts
     *
     * @mbg.generated Tue Mar 24 23:33:57 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(Posts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts
     *
     * @mbg.generated Tue Mar 24 23:33:57 CST 2020
     */
    int updateByPrimaryKey(Posts record);
}